### ISSUE TITLE
After ZoomIn And ZoomOut draw coordinates changed there positions

### ISSUE THREAD

**Issue by fayyaztech** [fayyaztech/android-canvas-zoom-and-draw-over-image#1]
hello, developer 
this app working fine as we want but the problem is only when i chnage position of image or zoom and zoom out the image the canvas draw on same position . please help me to fix this. 

thank you very much

**Comment by steam0111** [comment]
have the same problem

**Comment by tolik85** [comment]
Same here.
@steam0111 @fayyaztech Did you find any solution to this?

**Comment by fayyaztech** [comment]
@steam0111 yes I got the solution 
I user library [Doodle](https://github.com/1993hzw/Doodlel) 
https://github.com/1993hzw/Doodle
https://github.com/1993hzw/Doodle.git
read readme file carefully to implement into your application. all image editor functionality available. you can call and use in your application
